services:
  web:
    build: web
    image: ahersa/web-inmobiliario:latest
    restart: always
    environment:
      - SCRAPINGANT=${SCRAPINGANT}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
  scrapy:
    build: scrapy
    image: ahersa/scrapy-inmobiliario:latest
    restart: no
    environment:
      - SCRAPINGANT=${SCRAPINGANT}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      flask_network:
        ipv4_address: 192.168.100.6
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
networks:
  flask_network:
    ipam:
      config:
        - subnet: 192.168.100.0/24
volumes:
  postgres_data: null