services:
  web:
    image: ahersa/web-inmobiliario:latest
    container_name: inmobiliario-web
    platform: linux/arm64/v8
    restart: always
    environment:
      - SCRAPINGANT=${SCRAPINGANT}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
      - reverse-proxy
    ports: []
  scrapy:
    image: ahersa/scrapy-inmobiliario:latest
    container_name: inmobiliario-scrapy
    platform: linux/arm64/v8
    restart: no
    environment:
      - SCRAPINGANT=${SCRAPINGANT}
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    networks:
      - flask_network
  postgres:
    image: postgres:15
    container_name: inmobiliario-postgres
    platform: linux/arm64/v8
    restart: always
    environment:
      - POSTGRES_DB=inmobiliario_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - inmobiliario-tools_postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network
    ports:
      - 5432:5432
networks:
  flask_network: {}
  reverse-proxy:
    external: true
volumes:
  inmobiliario-tools_postgres_data:
    external: true