name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push web-inmobiliario image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ahersa/web-inmobiliario:latest

      - name: Build and push scrapy-inmobiliario image
        uses: docker/build-push-action@v4
        with:
          context: ./scrapy
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ahersa/scrapy-inmobiliario:latest

      - name: Build and push shiny-inmobiliario image
        uses: docker/build-push-action@v4
        with:
          context: ./shiny
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ahersa/shiny-inmobiliario:latest
