name: Deploy to VPS

on:
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_DIRECTORY: ${{ secrets.VPS_DIRECTORY }}
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd $VPS_DIRECTORY && sudo docker compose up -d --build"